---
- name: instance basic deploy
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    GCE_EMAIL:
    GCE_CREDENTIALS_FILE_PATH:
    GCE_PROJECT:
    instance_name:
    zone:

  tasks:
    - name: start instance
      gce:
          zone: "{{ zone }}"
          service_account_email: "{{ GCE_EMAIL }}"
          credentials_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
          project_id: "{{ GCE_PROJECT }}"
          name: "{{ instance_name }}"
          state: stopped
