---
- name: instance basic deploy
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    GCE_EMAIL:
    GCE_CREDENTIALS_FILE_PATH:
    GCE_PROJECT:
    instance_name:
    zone:

  tasks:
    - name: start instance
      zone: "{{ zone }}"
      name: {{ instance_name }}
      state: stopped
