---
- name: Deploy LAMP and LB
  hosts: "{{ instance_namea }},{{ instance_nameb }},{{ instance_namec }}"

  vars:
    instance_namea:
    instance_nameb:
    instance_namec:
    http_port: 80
    domain: example.com

  vars_files:


  roles:
    - gce_deploy
