---
- name: Deploy  LB
  hosts: localhost
  connection: local

  vars:
    instance_namea:
    instance_nameb:
    instance_namec:
    GCE_EMAIL:
    GCE_CREDENTIALS_FILE_PATH:
    GCE_PROJECT:
    zone:
    region:
    lb_name:


  vars_files:


  roles:
    - gce_lb
