---


- name: Launch instance
  gce:
      instance_names: "{{ instance_namea }}, {{ instance_nameb }}, {{ instance_namec }}"
      image: "{{ image }}"
      service_account_email: "{{ GCE_EMAIL }}"
      credentials_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
      project_id: "{{ GCE_PROJECT }}"
      zone: "{{ zone }}"
      disk_size: "{{ disk_size }}"
      machine_type: "{{ machine_type }}"
      tags: "{{ tags }}"
  register: gce
