---
- name: Instance Advanced Deploy
  hosts: localhost
  gather_facts: no

  vars:
    name_zonea:
    name_zoneb:
    image:
    zonea:
    zoneb:
    region:
    machine_type:
    GCE_PROJECT:
    GCE_CREDENTIALS_FILE_PATH:
    GCE_EMAIL:
    


  tasks:
    - name: Create an IP address for first instance
      gcp_compute_address:
        name: "{{ name_zonea }}-ip"
        region: "{{ region }}"
        project: "{{ GCE_PROJECT }}"
        service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
        service_account_email: "{{ GCE_EMAIL }}"
      register: gcea_ip
    - name: Bring up the first instance in the first zone.
      gcp_compute_instance:
        name: "{{ name_zonea }}"
        machine_type: "{{ machine_type }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "{{ image }}"
        network_interfaces:
          - access_configs:
              - name: External NAT
                nat_ip: "{{ gcea_ip }}"
                type: ONE_TO_ONE_NAT
        tags:
          items:
            - http-server
            - https-server
        zone: "{{ zonea }}"
        project: "{{ GCE_PROJECT }}"
        service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
        service_account_email: "{{ GCE_EMAIL }}"
      register: gcea
    - name: Create an IP address for second instance
      gcp_compute_address:
        name: "{{ name_zoneb }}-ip"
        region: "{{ region }}"
        project: "{{ GCE_PROJECT }}"
        service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
        service_account_email: "{{ GCE_EMAIL }}"
      register: gceb_ip
    - name: Bring up the instance in the second zone.
      gcp_compute_instance:
        name: "{{ name_zoneb }}"
        machine_type: "{{ machine_type }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "{{ image }}"
        network_interfaces:
          - access_configs:
              - name: External NAT
                nat_ip: "{{ gceb_ip }}"
                type: ONE_TO_ONE_NAT
        tags:
          items:
            - http-server
            - https-server
        zone: "{{ zoneb }}"
        project: "{{ GCE_PROJECT }}"
        service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
        service_account_email: "{{ GCE_EMAIL }}"
      register: gceb
