---
- name: instance basic deploy
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    machine_type:
    image:
    GCE_EMAIL:
    GCE_CREDENTIALS_FILE_PATH:
    GCE_PROJECT:
    instance_name:
    disk_size:
    machine_type:
    zone:
    tags:

  tasks:
    - name: Launch instance
      gce:
          instance_names: "{{ instance_name }}"
          image: "{{ image }}"
          service_account_email: "{{ GCE_EMAIL }}"
          credentials_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
          project_id: "{{ GCE_PROJECT }}"
          zone: "{{ zone }}"
          disk_size: "{{ disk_size }}"
          machine_type: "{{ machine_type }}"
          tags: "{{ tags }}"
      register: gce

    - name: Wait for ssh to come up
      wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60 ansible_user=ansiblegce
      with_items: "{{ gce.instance_data}}"
