---
- name: instance basic deploy
  hosts: localhost
  garther_facts: no
  connection: local

  vars:
    machine_type:
    image:
    service_account_email:
    credentials_file:
    project_id:
    instance_name:
    tags:

  tasks:
    - name: Launch instance
      gce:
          instance_names: "{{ instance_name }}"
          image: "{{ image }}"
          service_account_email: "{{ service_account_email }}"
          credentials_file: "{{ credentials_file }}"
          project_id: "{{ project_id }}"
          tags: "{{ tags }}"
      register: gce

    - name: Wait for ssh to come up
      wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60 ansible_user=ansiblegce
      with_items: "{{ gce.instance_data}}"
